language: node_js

node_js:
  - "8"

before_install:
  - 'nvm install-latest-npm'

env:
  matrix:
  - REACT=16.2
  - REACT=16.3
  - REACT=16.4

sudo: false

script:
  - npm run lint
  - npm run test
  - npm run test:cov

after_success:
  - ./node_modules/codecov/bin/codecov
